### ISSUE TITLE
mapping fields

### ISSUE THREAD

**Issue by JostCrow** [ChristopherRabotin/bungiesearch#155]
Maybe I missed it somewhere but I can't find it. Is there a way to add multiple fields. 

What I need is an extra mapping for fields. I want to use multiple fields. https://www.elastic.co/guide/en/elasticsearch/reference/current/_multi_fields.html. 
```Python
'fields': {
    "raw": {
        "type":  "string",
        "index": "not_analyzed"
    }
}
```

Is this possible now or not?

**Comment by ChristopherRabotin** [comment]
From the docs on multi field it seems like they are somewhat obsolete in the sense that you should now be using a normal field while specifying specifics in the definition of said field. These specifics should be supported by the hot fixes parameters when defining your mappings.
