### ISSUE TITLE
How would I query multiple ModelIndexes simultaneously?

### ISSUE THREAD

**Issue by jonesnc** [ChristopherRabotin/bungiesearch#159]
I'm looking through your docs, and this project looks pretty cool, but I have a question. I'm building a site-wide search feature that will query multiple models from multiple apps and display all of them in one, unified interface.

It appears that your `ModelIndex` associates a single `Model` to a single `Index`. Is there any way to query multiple `ModelIndex`es in a single expression?

**Comment by ChristopherRabotin** [comment]
If I recall correctly (I haven't used this project in about a year now to be honest), it is possible to use the main `Bungiesearch` object to pass a list of indices to search. However, this functionality does not directl integrate with the `ModelIndex` classes, so you need to do the mapping to Django objects yourself.
Another solution is to run the queries independently and assemble all the results together in the app. Last time I was using this, we had multiple models to search, some defined on different indices, and we simply had a list of these Django model (e.g. `[Article, Patent]`) and iterate through that. Each had its own index defined via a ModelIndex (e.g. `Article` was associated to the `content_new` index and `Patent` to the `content` index). The query would be applied to each model, the results aggregated in a list, and that list had some further processing before being returned by the API.

Hope this helps.

**Comment by jonesnc** [comment]
Do you think the "query all models and assemble the results" strategy will grossly affect performance as our indexes grow in size?

This also sounds like it could get tricky if I need to correctly sort multiple result sets with different scores, boosts, etc.

**Comment by ChristopherRabotin** [comment]
The scores and boosts happen at the elasticsearch level, so the performance of these depend solely on the size and performance of your cluster. Concerning the assembling of results, it really depends a lot on how much data you plan on grabbing from each index, and on whether you also request the actual object from the database, or do the assembly solely from the ES response (which has a dictionary with all the requested fields for each item returned). In my case, we had seven models and would return 20 or 25 items of each model (so 140 to 170 items), did another in-app filter of the data using only the ES response, and then trimmed down the data based on what we actually wanted returned to the requester.

**Comment by jonesnc** [comment]
I could probably do something like that.

Since I'm querying each index in isolation, will the scores be skewed or inaccurate in some way since each index is not aware of the other indexes' matching documents?

**Comment by ChristopherRabotin** [comment]
Yes, the scores will be skewed, so you will need some kind of
normalization. Not sure if ES now provides a way to find the highest score
attainable but until last year it could not. Hence, in my application, we
would normalize based on the highest score returned by the query. That's
far from perfect though, and we had a number of odd results that way.

**Comment by jonesnc** [comment]
Ah, ok. I think I'll revert back to haystack usage for now, but if multiple index searching ever becomes a feature of this project, please let me know!

**Comment by ChristopherRabotin** [comment]
Okay, good luck. I hope that Haystack has changed in speed for the past two years as it was painfully slow on ES when I started bungiesearch. That was one of the reasons for starting this project.

P.S.: Now that I write this, I do recall reading that Haystack's ES layer is now done by the ES team via elasticsearch_dsl so it probably is faster now.

**Comment by jonesnc** [comment]
I didn't realize that, thanks for the heads up. I'll keep an eye on their progress. I think there's development work going into modernizing the elasticsearch backend, so we'll see what happens.

Thanks again for all of your help and timely replies!
