### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by ChristopherRabotin** [ChristopherRabotin/bungiesearch#87]
Elasticsearch-dsl-py supports Python 3. However, testing bungiesearch on Python 3 [fails with a Runtime Error](https://travis-ci.org/Sparrho/bungiesearch/jobs/68166833).

The code in release 1.1.0 will have some initial steps towards Python 3 support, but as the build shows, the support isn't here yet.

**Comment by terite** [comment]
I think you get to close this issue :)
